// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `android.os.Build$Partition`
class Build$Partition extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Build$Partition> $type;

  @jni$_.internal
  Build$Partition.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/os/Build$Partition');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$Partition?> nullableType =
      $Build$Partition$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$Partition> type = $Build$Partition$Type$();
  static final _id_PARTITION_NAME_SYSTEM = _class.staticFieldId(
    r'PARTITION_NAME_SYSTEM',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PARTITION_NAME_SYSTEM`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get PARTITION_NAME_SYSTEM => _id_PARTITION_NAME_SYSTEM
      .get(_class, const jni$_.$JString$NullableType$());

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_getBuildTimeMillis = _class.instanceMethodId(
    r'getBuildTimeMillis',
    r'()J',
  );

  static final _getBuildTimeMillis =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public long getBuildTimeMillis()`
  int getBuildTimeMillis() {
    return _getBuildTimeMillis(
      reference.pointer,
      _id_getBuildTimeMillis as jni$_.JMethodIDPtr,
    ).long;
  }

  static final _id_getFingerprint = _class.instanceMethodId(
    r'getFingerprint',
    r'()Ljava/lang/String;',
  );

  static final _getFingerprint =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getFingerprint()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getFingerprint() {
    return _getFingerprint(
      reference.pointer,
      _id_getFingerprint as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getName = _class.instanceMethodId(
    r'getName',
    r'()Ljava/lang/String;',
  );

  static final _getName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String getName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getName() {
    return _getName(
      reference.pointer,
      _id_getName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }
}

final class $Build$Partition$NullableType$
    extends jni$_.JType<Build$Partition?> {
  @jni$_.internal
  const $Build$Partition$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$Partition;';

  @jni$_.internal
  @core$_.override
  Build$Partition? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Build$Partition.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$Partition?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$Partition$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$Partition$NullableType$) &&
        other is $Build$Partition$NullableType$;
  }
}

final class $Build$Partition$Type$ extends jni$_.JType<Build$Partition> {
  @jni$_.internal
  const $Build$Partition$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$Partition;';

  @jni$_.internal
  @core$_.override
  Build$Partition fromReference(jni$_.JReference reference) =>
      Build$Partition.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$Partition?> get nullableType =>
      const $Build$Partition$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$Partition$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$Partition$Type$) &&
        other is $Build$Partition$Type$;
  }
}

/// from: `android.os.Build$VERSION`
class Build$VERSION extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Build$VERSION> $type;

  @jni$_.internal
  Build$VERSION.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/os/Build$VERSION');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION?> nullableType =
      $Build$VERSION$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION> type = $Build$VERSION$Type$();
  static final _id_BASE_OS = _class.staticFieldId(
    r'BASE_OS',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String BASE_OS`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get BASE_OS =>
      _id_BASE_OS.get(_class, const jni$_.$JString$NullableType$());

  static final _id_CODENAME = _class.staticFieldId(
    r'CODENAME',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String CODENAME`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get CODENAME =>
      _id_CODENAME.get(_class, const jni$_.$JString$NullableType$());

  static final _id_INCREMENTAL = _class.staticFieldId(
    r'INCREMENTAL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String INCREMENTAL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get INCREMENTAL =>
      _id_INCREMENTAL.get(_class, const jni$_.$JString$NullableType$());

  static final _id_MEDIA_PERFORMANCE_CLASS = _class.staticFieldId(
    r'MEDIA_PERFORMANCE_CLASS',
    r'I',
  );

  /// from: `static public final int MEDIA_PERFORMANCE_CLASS`
  static int get MEDIA_PERFORMANCE_CLASS =>
      _id_MEDIA_PERFORMANCE_CLASS.get(_class, const jni$_.jintType());

  static final _id_PREVIEW_SDK_INT = _class.staticFieldId(
    r'PREVIEW_SDK_INT',
    r'I',
  );

  /// from: `static public final int PREVIEW_SDK_INT`
  static int get PREVIEW_SDK_INT =>
      _id_PREVIEW_SDK_INT.get(_class, const jni$_.jintType());

  static final _id_RELEASE = _class.staticFieldId(
    r'RELEASE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String RELEASE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get RELEASE =>
      _id_RELEASE.get(_class, const jni$_.$JString$NullableType$());

  static final _id_RELEASE_OR_CODENAME = _class.staticFieldId(
    r'RELEASE_OR_CODENAME',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String RELEASE_OR_CODENAME`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get RELEASE_OR_CODENAME =>
      _id_RELEASE_OR_CODENAME.get(_class, const jni$_.$JString$NullableType$());

  static final _id_RELEASE_OR_PREVIEW_DISPLAY = _class.staticFieldId(
    r'RELEASE_OR_PREVIEW_DISPLAY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String RELEASE_OR_PREVIEW_DISPLAY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get RELEASE_OR_PREVIEW_DISPLAY =>
      _id_RELEASE_OR_PREVIEW_DISPLAY.get(
        _class,
        const jni$_.$JString$NullableType$(),
      );

  static final _id_SDK = _class.staticFieldId(r'SDK', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String SDK`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get SDK =>
      _id_SDK.get(_class, const jni$_.$JString$NullableType$());

  static final _id_SDK_INT = _class.staticFieldId(r'SDK_INT', r'I');

  /// from: `static public final int SDK_INT`
  static int get SDK_INT => _id_SDK_INT.get(_class, const jni$_.jintType());

  static final _id_SDK_INT_FULL = _class.staticFieldId(r'SDK_INT_FULL', r'I');

  /// from: `static public final int SDK_INT_FULL`
  static int get SDK_INT_FULL =>
      _id_SDK_INT_FULL.get(_class, const jni$_.jintType());

  static final _id_SECURITY_PATCH = _class.staticFieldId(
    r'SECURITY_PATCH',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String SECURITY_PATCH`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get SECURITY_PATCH =>
      _id_SECURITY_PATCH.get(_class, const jni$_.$JString$NullableType$());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Build$VERSION() {
    return Build$VERSION.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }
}

final class $Build$VERSION$NullableType$ extends jni$_.JType<Build$VERSION?> {
  @jni$_.internal
  const $Build$VERSION$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION;';

  @jni$_.internal
  @core$_.override
  Build$VERSION? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Build$VERSION.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$VERSION?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$VERSION$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$VERSION$NullableType$) &&
        other is $Build$VERSION$NullableType$;
  }
}

final class $Build$VERSION$Type$ extends jni$_.JType<Build$VERSION> {
  @jni$_.internal
  const $Build$VERSION$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION;';

  @jni$_.internal
  @core$_.override
  Build$VERSION fromReference(jni$_.JReference reference) =>
      Build$VERSION.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$VERSION?> get nullableType =>
      const $Build$VERSION$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$VERSION$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$VERSION$Type$) &&
        other is $Build$VERSION$Type$;
  }
}

/// from: `android.os.Build$VERSION_CODES`
class Build$VERSION_CODES extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Build$VERSION_CODES> $type;

  @jni$_.internal
  Build$VERSION_CODES.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/os/Build$VERSION_CODES');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION_CODES?> nullableType =
      $Build$VERSION_CODES$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION_CODES> type =
      $Build$VERSION_CODES$Type$();

  /// from: `static public final int BAKLAVA`
  static const BAKLAVA = 36;

  /// from: `static public final int BASE`
  static const BASE = 1;

  /// from: `static public final int BASE_1_1`
  static const BASE_1_1 = 2;

  /// from: `static public final int CUPCAKE`
  static const CUPCAKE = 3;

  /// from: `static public final int CUR_DEVELOPMENT`
  static const CUR_DEVELOPMENT = 10000;

  /// from: `static public final int DONUT`
  static const DONUT = 4;

  /// from: `static public final int ECLAIR`
  static const ECLAIR = 5;

  /// from: `static public final int ECLAIR_0_1`
  static const ECLAIR_0_1 = 6;

  /// from: `static public final int ECLAIR_MR1`
  static const ECLAIR_MR1 = 7;

  /// from: `static public final int FROYO`
  static const FROYO = 8;

  /// from: `static public final int GINGERBREAD`
  static const GINGERBREAD = 9;

  /// from: `static public final int GINGERBREAD_MR1`
  static const GINGERBREAD_MR1 = 10;

  /// from: `static public final int HONEYCOMB`
  static const HONEYCOMB = 11;

  /// from: `static public final int HONEYCOMB_MR1`
  static const HONEYCOMB_MR1 = 12;

  /// from: `static public final int HONEYCOMB_MR2`
  static const HONEYCOMB_MR2 = 13;

  /// from: `static public final int ICE_CREAM_SANDWICH`
  static const ICE_CREAM_SANDWICH = 14;

  /// from: `static public final int ICE_CREAM_SANDWICH_MR1`
  static const ICE_CREAM_SANDWICH_MR1 = 15;

  /// from: `static public final int JELLY_BEAN`
  static const JELLY_BEAN = 16;

  /// from: `static public final int JELLY_BEAN_MR1`
  static const JELLY_BEAN_MR1 = 17;

  /// from: `static public final int JELLY_BEAN_MR2`
  static const JELLY_BEAN_MR2 = 18;

  /// from: `static public final int KITKAT`
  static const KITKAT = 19;

  /// from: `static public final int KITKAT_WATCH`
  static const KITKAT_WATCH = 20;

  /// from: `static public final int LOLLIPOP`
  static const LOLLIPOP = 21;

  /// from: `static public final int LOLLIPOP_MR1`
  static const LOLLIPOP_MR1 = 22;

  /// from: `static public final int M`
  static const M = 23;

  /// from: `static public final int N`
  static const N = 24;

  /// from: `static public final int N_MR1`
  static const N_MR1 = 25;

  /// from: `static public final int O`
  static const O = 26;

  /// from: `static public final int O_MR1`
  static const O_MR1 = 27;

  /// from: `static public final int P`
  static const P = 28;

  /// from: `static public final int Q`
  static const Q = 29;

  /// from: `static public final int R`
  static const R = 30;

  /// from: `static public final int S`
  static const S = 31;

  /// from: `static public final int S_V2`
  static const S_V2 = 32;

  /// from: `static public final int TIRAMISU`
  static const TIRAMISU = 33;

  /// from: `static public final int UPSIDE_DOWN_CAKE`
  static const UPSIDE_DOWN_CAKE = 34;

  /// from: `static public final int VANILLA_ICE_CREAM`
  static const VANILLA_ICE_CREAM = 35;
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Build$VERSION_CODES() {
    return Build$VERSION_CODES.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }
}

final class $Build$VERSION_CODES$NullableType$
    extends jni$_.JType<Build$VERSION_CODES?> {
  @jni$_.internal
  const $Build$VERSION_CODES$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION_CODES;';

  @jni$_.internal
  @core$_.override
  Build$VERSION_CODES? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Build$VERSION_CODES.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$VERSION_CODES?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$VERSION_CODES$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$VERSION_CODES$NullableType$) &&
        other is $Build$VERSION_CODES$NullableType$;
  }
}

final class $Build$VERSION_CODES$Type$
    extends jni$_.JType<Build$VERSION_CODES> {
  @jni$_.internal
  const $Build$VERSION_CODES$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION_CODES;';

  @jni$_.internal
  @core$_.override
  Build$VERSION_CODES fromReference(jni$_.JReference reference) =>
      Build$VERSION_CODES.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$VERSION_CODES?> get nullableType =>
      const $Build$VERSION_CODES$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$VERSION_CODES$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$VERSION_CODES$Type$) &&
        other is $Build$VERSION_CODES$Type$;
  }
}

/// from: `android.os.Build$VERSION_CODES_FULL`
class Build$VERSION_CODES_FULL extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Build$VERSION_CODES_FULL> $type;

  @jni$_.internal
  Build$VERSION_CODES_FULL.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'android/os/Build$VERSION_CODES_FULL',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION_CODES_FULL?> nullableType =
      $Build$VERSION_CODES_FULL$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION_CODES_FULL> type =
      $Build$VERSION_CODES_FULL$Type$();

  /// from: `static public final int BAKLAVA`
  static const BAKLAVA = 3600000;

  /// from: `static public final int BASE`
  static const BASE = 100000;

  /// from: `static public final int BASE_1_1`
  static const BASE_1_1 = 200000;

  /// from: `static public final int CUPCAKE`
  static const CUPCAKE = 300000;

  /// from: `static public final int DONUT`
  static const DONUT = 400000;

  /// from: `static public final int ECLAIR`
  static const ECLAIR = 500000;

  /// from: `static public final int ECLAIR_0_1`
  static const ECLAIR_0_1 = 600000;

  /// from: `static public final int ECLAIR_MR1`
  static const ECLAIR_MR1 = 700000;

  /// from: `static public final int FROYO`
  static const FROYO = 800000;

  /// from: `static public final int GINGERBREAD`
  static const GINGERBREAD = 900000;

  /// from: `static public final int GINGERBREAD_MR1`
  static const GINGERBREAD_MR1 = 1000000;

  /// from: `static public final int HONEYCOMB`
  static const HONEYCOMB = 1100000;

  /// from: `static public final int HONEYCOMB_MR1`
  static const HONEYCOMB_MR1 = 1200000;

  /// from: `static public final int HONEYCOMB_MR2`
  static const HONEYCOMB_MR2 = 1300000;

  /// from: `static public final int ICE_CREAM_SANDWICH`
  static const ICE_CREAM_SANDWICH = 1400000;

  /// from: `static public final int ICE_CREAM_SANDWICH_MR1`
  static const ICE_CREAM_SANDWICH_MR1 = 1500000;

  /// from: `static public final int JELLY_BEAN`
  static const JELLY_BEAN = 1600000;

  /// from: `static public final int JELLY_BEAN_MR1`
  static const JELLY_BEAN_MR1 = 1700000;

  /// from: `static public final int JELLY_BEAN_MR2`
  static const JELLY_BEAN_MR2 = 1800000;

  /// from: `static public final int KITKAT`
  static const KITKAT = 1900000;

  /// from: `static public final int KITKAT_WATCH`
  static const KITKAT_WATCH = 2000000;

  /// from: `static public final int LOLLIPOP`
  static const LOLLIPOP = 2100000;

  /// from: `static public final int LOLLIPOP_MR1`
  static const LOLLIPOP_MR1 = 2200000;

  /// from: `static public final int M`
  static const M = 2300000;

  /// from: `static public final int N`
  static const N = 2400000;

  /// from: `static public final int N_MR1`
  static const N_MR1 = 2500000;

  /// from: `static public final int O`
  static const O = 2600000;

  /// from: `static public final int O_MR1`
  static const O_MR1 = 2700000;

  /// from: `static public final int P`
  static const P = 2800000;

  /// from: `static public final int Q`
  static const Q = 2900000;

  /// from: `static public final int R`
  static const R = 3000000;

  /// from: `static public final int S`
  static const S = 3100000;

  /// from: `static public final int S_V2`
  static const S_V2 = 3200000;

  /// from: `static public final int TIRAMISU`
  static const TIRAMISU = 3300000;

  /// from: `static public final int UPSIDE_DOWN_CAKE`
  static const UPSIDE_DOWN_CAKE = 3400000;

  /// from: `static public final int VANILLA_ICE_CREAM`
  static const VANILLA_ICE_CREAM = 3500000;
}

final class $Build$VERSION_CODES_FULL$NullableType$
    extends jni$_.JType<Build$VERSION_CODES_FULL?> {
  @jni$_.internal
  const $Build$VERSION_CODES_FULL$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION_CODES_FULL;';

  @jni$_.internal
  @core$_.override
  Build$VERSION_CODES_FULL? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : Build$VERSION_CODES_FULL.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$VERSION_CODES_FULL?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$VERSION_CODES_FULL$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$VERSION_CODES_FULL$NullableType$) &&
        other is $Build$VERSION_CODES_FULL$NullableType$;
  }
}

final class $Build$VERSION_CODES_FULL$Type$
    extends jni$_.JType<Build$VERSION_CODES_FULL> {
  @jni$_.internal
  const $Build$VERSION_CODES_FULL$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION_CODES_FULL;';

  @jni$_.internal
  @core$_.override
  Build$VERSION_CODES_FULL fromReference(jni$_.JReference reference) =>
      Build$VERSION_CODES_FULL.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build$VERSION_CODES_FULL?> get nullableType =>
      const $Build$VERSION_CODES_FULL$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$VERSION_CODES_FULL$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$VERSION_CODES_FULL$Type$) &&
        other is $Build$VERSION_CODES_FULL$Type$;
  }
}

/// from: `android.os.Build`
class Build extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Build> $type;

  @jni$_.internal
  Build.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'android/os/Build');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build?> nullableType = $Build$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build> type = $Build$Type$();
  static final _id_BOARD = _class.staticFieldId(
    r'BOARD',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String BOARD`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get BOARD =>
      _id_BOARD.get(_class, const jni$_.$JString$NullableType$());

  static final _id_BOOTLOADER = _class.staticFieldId(
    r'BOOTLOADER',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String BOOTLOADER`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get BOOTLOADER =>
      _id_BOOTLOADER.get(_class, const jni$_.$JString$NullableType$());

  static final _id_BRAND = _class.staticFieldId(
    r'BRAND',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String BRAND`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get BRAND =>
      _id_BRAND.get(_class, const jni$_.$JString$NullableType$());

  static final _id_CPU_ABI = _class.staticFieldId(
    r'CPU_ABI',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String CPU_ABI`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get CPU_ABI =>
      _id_CPU_ABI.get(_class, const jni$_.$JString$NullableType$());

  static final _id_CPU_ABI2 = _class.staticFieldId(
    r'CPU_ABI2',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String CPU_ABI2`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get CPU_ABI2 =>
      _id_CPU_ABI2.get(_class, const jni$_.$JString$NullableType$());

  static final _id_DEVICE = _class.staticFieldId(
    r'DEVICE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String DEVICE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get DEVICE =>
      _id_DEVICE.get(_class, const jni$_.$JString$NullableType$());

  static final _id_DISPLAY = _class.staticFieldId(
    r'DISPLAY',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String DISPLAY`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get DISPLAY =>
      _id_DISPLAY.get(_class, const jni$_.$JString$NullableType$());

  static final _id_FINGERPRINT = _class.staticFieldId(
    r'FINGERPRINT',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String FINGERPRINT`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get FINGERPRINT =>
      _id_FINGERPRINT.get(_class, const jni$_.$JString$NullableType$());

  static final _id_HARDWARE = _class.staticFieldId(
    r'HARDWARE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String HARDWARE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get HARDWARE =>
      _id_HARDWARE.get(_class, const jni$_.$JString$NullableType$());

  static final _id_HOST = _class.staticFieldId(r'HOST', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String HOST`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get HOST =>
      _id_HOST.get(_class, const jni$_.$JString$NullableType$());

  static final _id_ID = _class.staticFieldId(r'ID', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String ID`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get ID =>
      _id_ID.get(_class, const jni$_.$JString$NullableType$());

  static final _id_MANUFACTURER = _class.staticFieldId(
    r'MANUFACTURER',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String MANUFACTURER`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get MANUFACTURER =>
      _id_MANUFACTURER.get(_class, const jni$_.$JString$NullableType$());

  static final _id_MODEL = _class.staticFieldId(
    r'MODEL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String MODEL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get MODEL =>
      _id_MODEL.get(_class, const jni$_.$JString$NullableType$());

  static final _id_ODM_SKU = _class.staticFieldId(
    r'ODM_SKU',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String ODM_SKU`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get ODM_SKU =>
      _id_ODM_SKU.get(_class, const jni$_.$JString$NullableType$());

  static final _id_PRODUCT = _class.staticFieldId(
    r'PRODUCT',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PRODUCT`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get PRODUCT =>
      _id_PRODUCT.get(_class, const jni$_.$JString$NullableType$());

  static final _id_RADIO = _class.staticFieldId(
    r'RADIO',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String RADIO`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get RADIO =>
      _id_RADIO.get(_class, const jni$_.$JString$NullableType$());

  static final _id_SERIAL = _class.staticFieldId(
    r'SERIAL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String SERIAL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get SERIAL =>
      _id_SERIAL.get(_class, const jni$_.$JString$NullableType$());

  static final _id_SKU = _class.staticFieldId(r'SKU', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String SKU`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get SKU =>
      _id_SKU.get(_class, const jni$_.$JString$NullableType$());

  static final _id_SOC_MANUFACTURER = _class.staticFieldId(
    r'SOC_MANUFACTURER',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String SOC_MANUFACTURER`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get SOC_MANUFACTURER =>
      _id_SOC_MANUFACTURER.get(_class, const jni$_.$JString$NullableType$());

  static final _id_SOC_MODEL = _class.staticFieldId(
    r'SOC_MODEL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String SOC_MODEL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get SOC_MODEL =>
      _id_SOC_MODEL.get(_class, const jni$_.$JString$NullableType$());

  static final _id_SUPPORTED_32_BIT_ABIS = _class.staticFieldId(
    r'SUPPORTED_32_BIT_ABIS',
    r'[Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String[] SUPPORTED_32_BIT_ABIS`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<jni$_.JString?>? get SUPPORTED_32_BIT_ABIS =>
      _id_SUPPORTED_32_BIT_ABIS.get(
        _class,
        const jni$_.$JArray$NullableType$<jni$_.JString?>(
          jni$_.$JString$NullableType$(),
        ),
      );

  static final _id_SUPPORTED_64_BIT_ABIS = _class.staticFieldId(
    r'SUPPORTED_64_BIT_ABIS',
    r'[Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String[] SUPPORTED_64_BIT_ABIS`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<jni$_.JString?>? get SUPPORTED_64_BIT_ABIS =>
      _id_SUPPORTED_64_BIT_ABIS.get(
        _class,
        const jni$_.$JArray$NullableType$<jni$_.JString?>(
          jni$_.$JString$NullableType$(),
        ),
      );

  static final _id_SUPPORTED_ABIS = _class.staticFieldId(
    r'SUPPORTED_ABIS',
    r'[Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String[] SUPPORTED_ABIS`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JArray<jni$_.JString?>? get SUPPORTED_ABIS =>
      _id_SUPPORTED_ABIS.get(
        _class,
        const jni$_.$JArray$NullableType$<jni$_.JString?>(
          jni$_.$JString$NullableType$(),
        ),
      );

  static final _id_TAGS = _class.staticFieldId(r'TAGS', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String TAGS`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get TAGS =>
      _id_TAGS.get(_class, const jni$_.$JString$NullableType$());

  static final _id_TIME = _class.staticFieldId(r'TIME', r'J');

  /// from: `static public final long TIME`
  static int get TIME => _id_TIME.get(_class, const jni$_.jlongType());

  static final _id_TYPE = _class.staticFieldId(r'TYPE', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String TYPE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get TYPE =>
      _id_TYPE.get(_class, const jni$_.$JString$NullableType$());

  static final _id_UNKNOWN = _class.staticFieldId(
    r'UNKNOWN',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String UNKNOWN`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get UNKNOWN =>
      _id_UNKNOWN.get(_class, const jni$_.$JString$NullableType$());

  static final _id_USER = _class.staticFieldId(r'USER', r'Ljava/lang/String;');

  /// from: `static public final java.lang.String USER`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get USER =>
      _id_USER.get(_class, const jni$_.$JString$NullableType$());

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Build() {
    return Build.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_getFingerprintedPartitions = _class.staticMethodId(
    r'getFingerprintedPartitions',
    r'()Ljava/util/List;',
  );

  static final _getFingerprintedPartitions =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.util.List<android.os.Build$Partition> getFingerprintedPartitions()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JList<Build$Partition?>? getFingerprintedPartitions() {
    return _getFingerprintedPartitions(
      _class.reference.pointer,
      _id_getFingerprintedPartitions as jni$_.JMethodIDPtr,
    ).object<jni$_.JList<Build$Partition?>?>(
      const jni$_.$JList$NullableType$<Build$Partition?>(
        $Build$Partition$NullableType$(),
      ),
    );
  }

  static final _id_getMajorSdkVersion = _class.staticMethodId(
    r'getMajorSdkVersion',
    r'(I)I',
  );

  static final _getMajorSdkVersion =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `static public int getMajorSdkVersion(int i)`
  static int getMajorSdkVersion(int i) {
    return _getMajorSdkVersion(
      _class.reference.pointer,
      _id_getMajorSdkVersion as jni$_.JMethodIDPtr,
      i,
    ).integer;
  }

  static final _id_getMinorSdkVersion = _class.staticMethodId(
    r'getMinorSdkVersion',
    r'(I)I',
  );

  static final _getMinorSdkVersion =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `static public int getMinorSdkVersion(int i)`
  static int getMinorSdkVersion(int i) {
    return _getMinorSdkVersion(
      _class.reference.pointer,
      _id_getMinorSdkVersion as jni$_.JMethodIDPtr,
      i,
    ).integer;
  }

  static final _id_getRadioVersion = _class.staticMethodId(
    r'getRadioVersion',
    r'()Ljava/lang/String;',
  );

  static final _getRadioVersion =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String getRadioVersion()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getRadioVersion() {
    return _getRadioVersion(
      _class.reference.pointer,
      _id_getRadioVersion as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getSerial = _class.staticMethodId(
    r'getSerial',
    r'()Ljava/lang/String;',
  );

  static final _getSerial =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String getSerial()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getSerial() {
    return _getSerial(
      _class.reference.pointer,
      _id_getSerial as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $Build$NullableType$ extends jni$_.JType<Build?> {
  @jni$_.internal
  const $Build$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build;';

  @jni$_.internal
  @core$_.override
  Build? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Build.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$NullableType$) &&
        other is $Build$NullableType$;
  }
}

final class $Build$Type$ extends jni$_.JType<Build> {
  @jni$_.internal
  const $Build$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build;';

  @jni$_.internal
  @core$_.override
  Build fromReference(jni$_.JReference reference) =>
      Build.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Build?> get nullableType => const $Build$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Build$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Build$Type$) && other is $Build$Type$;
  }
}

/// from: `java.util.HashMap`
class HashMap<$K extends jni$_.JObject?, $V extends jni$_.JObject?>
    extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<HashMap<$K, $V>> $type;

  @jni$_.internal
  final jni$_.JType<$K> K;

  @jni$_.internal
  final jni$_.JType<$V> V;

  @jni$_.internal
  HashMap.fromReference(this.K, this.V, jni$_.JReference reference)
    : $type = type<$K, $V>(K, V),
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'java/util/HashMap');

  /// The type which includes information such as the signature of this class.
  static jni$_.JType<HashMap<$K, $V>?> nullableType<
    $K extends jni$_.JObject?,
    $V extends jni$_.JObject?
  >(jni$_.JType<$K> K, jni$_.JType<$V> V) {
    return $HashMap$NullableType$<$K, $V>(K, V);
  }

  /// The type which includes information such as the signature of this class.
  static jni$_.JType<HashMap<$K, $V>> type<
    $K extends jni$_.JObject?,
    $V extends jni$_.JObject?
  >(jni$_.JType<$K> K, jni$_.JType<$V> V) {
    return $HashMap$Type$<$K, $V>(K, V);
  }

  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory HashMap({required jni$_.JType<$K> K, required jni$_.JType<$V> V}) {
    return HashMap<$K, $V>.fromReference(
      K,
      V,
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(r'(I)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `public void <init>(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory HashMap.new$1(
    int i, {
    required jni$_.JType<$K> K,
    required jni$_.JType<$V> V,
  }) {
    return HashMap<$K, $V>.fromReference(
      K,
      V,
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        i,
      ).reference,
    );
  }

  static final _id_new$2 = _class.constructorId(r'(IF)V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Double)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              double,
            )
          >();

  /// from: `public void <init>(int i, float f)`
  /// The returned object must be released after use, by calling the [release] method.
  factory HashMap.new$2(
    int i,
    double f, {
    required jni$_.JType<$K> K,
    required jni$_.JType<$V> V,
  }) {
    return HashMap<$K, $V>.fromReference(
      K,
      V,
      _new$2(
        _class.reference.pointer,
        _id_new$2 as jni$_.JMethodIDPtr,
        i,
        f,
      ).reference,
    );
  }

  static final _id_new$3 = _class.constructorId(r'(Ljava/util/Map;)V');

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.util.Map<? extends K, ? extends V> map)`
  /// The returned object must be released after use, by calling the [release] method.
  factory HashMap.new$3(
    jni$_.JMap<$K?, $V?>? map, {
    required jni$_.JType<$K> K,
    required jni$_.JType<$V> V,
  }) {
    final _$map = map?.reference ?? jni$_.jNullReference;
    return HashMap<$K, $V>.fromReference(
      K,
      V,
      _new$3(
        _class.reference.pointer,
        _id_new$3 as jni$_.JMethodIDPtr,
        _$map.pointer,
      ).reference,
    );
  }

  static final _id_clear = _class.instanceMethodId(r'clear', r'()V');

  static final _clear =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void clear()`
  void clear() {
    _clear(reference.pointer, _id_clear as jni$_.JMethodIDPtr).check();
  }

  static final _id_clone = _class.instanceMethodId(
    r'clone',
    r'()Ljava/lang/Object;',
  );

  static final _clone =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.Object clone()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? clone() {
    return _clone(
      reference.pointer,
      _id_clone as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }

  static final _id_compute = _class.instanceMethodId(
    r'compute',
    r'(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;',
  );

  static final _compute =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V compute(K object, java.util.function.BiFunction<? super K, ? super V, ? extends V> biFunction)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? compute($K? object, jni$_.JObject? biFunction) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$biFunction = biFunction?.reference ?? jni$_.jNullReference;
    return _compute(
      reference.pointer,
      _id_compute as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$biFunction.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_computeIfAbsent = _class.instanceMethodId(
    r'computeIfAbsent',
    r'(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object;',
  );

  static final _computeIfAbsent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V computeIfAbsent(K object, java.util.function.Function<? super K, ? extends V> function)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? computeIfAbsent($K? object, jni$_.JObject? function) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$function = function?.reference ?? jni$_.jNullReference;
    return _computeIfAbsent(
      reference.pointer,
      _id_computeIfAbsent as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$function.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_computeIfPresent = _class.instanceMethodId(
    r'computeIfPresent',
    r'(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;',
  );

  static final _computeIfPresent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V computeIfPresent(K object, java.util.function.BiFunction<? super K, ? super V, ? extends V> biFunction)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? computeIfPresent($K? object, jni$_.JObject? biFunction) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$biFunction = biFunction?.reference ?? jni$_.jNullReference;
    return _computeIfPresent(
      reference.pointer,
      _id_computeIfPresent as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$biFunction.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_containsKey = _class.instanceMethodId(
    r'containsKey',
    r'(Ljava/lang/Object;)Z',
  );

  static final _containsKey =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean containsKey(java.lang.Object object)`
  bool containsKey(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _containsKey(
      reference.pointer,
      _id_containsKey as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_containsValue = _class.instanceMethodId(
    r'containsValue',
    r'(Ljava/lang/Object;)Z',
  );

  static final _containsValue =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean containsValue(java.lang.Object object)`
  bool containsValue(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _containsValue(
      reference.pointer,
      _id_containsValue as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_entrySet = _class.instanceMethodId(
    r'entrySet',
    r'()Ljava/util/Set;',
  );

  static final _entrySet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Set<java.util.Map$Entry<K, V>> entrySet()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JSet<jni$_.JObject?>? entrySet() {
    return _entrySet(
      reference.pointer,
      _id_entrySet as jni$_.JMethodIDPtr,
    ).object<jni$_.JSet<jni$_.JObject?>?>(
      const jni$_.$JSet$NullableType$<jni$_.JObject?>(
        jni$_.$JObject$NullableType$(),
      ),
    );
  }

  static final _id_forEach = _class.instanceMethodId(
    r'forEach',
    r'(Ljava/util/function/BiConsumer;)V',
  );

  static final _forEach =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void forEach(java.util.function.BiConsumer<? super K, ? super V> biConsumer)`
  void forEach(jni$_.JObject? biConsumer) {
    final _$biConsumer = biConsumer?.reference ?? jni$_.jNullReference;
    _forEach(
      reference.pointer,
      _id_forEach as jni$_.JMethodIDPtr,
      _$biConsumer.pointer,
    ).check();
  }

  static final _id_get = _class.instanceMethodId(
    r'get',
    r'(Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _get =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V get(java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? get(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _get(
      reference.pointer,
      _id_get as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_getOrDefault = _class.instanceMethodId(
    r'getOrDefault',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _getOrDefault =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V getOrDefault(java.lang.Object object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? getOrDefault(jni$_.JObject? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _getOrDefault(
      reference.pointer,
      _id_getOrDefault as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_isEmpty = _class.instanceMethodId(r'isEmpty', r'()Z');

  static final _isEmpty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isEmpty()`
  bool isEmpty() {
    return _isEmpty(
      reference.pointer,
      _id_isEmpty as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_keySet = _class.instanceMethodId(
    r'keySet',
    r'()Ljava/util/Set;',
  );

  static final _keySet =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Set<K> keySet()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JSet<$K?>? keySet() {
    return _keySet(
      reference.pointer,
      _id_keySet as jni$_.JMethodIDPtr,
    ).object<jni$_.JSet<$K?>?>(jni$_.$JSet$NullableType$<$K?>(K.nullableType));
  }

  static final _id_merge = _class.instanceMethodId(
    r'merge',
    r'(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;',
  );

  static final _merge =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V merge(K object, V object1, java.util.function.BiFunction<? super V, ? super V, ? extends V> biFunction)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? merge($K? object, $V? object1, jni$_.JObject? biFunction) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    final _$biFunction = biFunction?.reference ?? jni$_.jNullReference;
    return _merge(
      reference.pointer,
      _id_merge as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
      _$biFunction.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_newHashMap = _class.staticMethodId(
    r'newHashMap',
    r'(I)Ljava/util/HashMap;',
  );

  static final _newHashMap =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `static public java.util.HashMap<K, V> newHashMap(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static HashMap<$K?, $V?>? newHashMap<
    $K extends jni$_.JObject?,
    $V extends jni$_.JObject?
  >(int i, {required jni$_.JType<$K> K, required jni$_.JType<$V> V}) {
    return _newHashMap(
      _class.reference.pointer,
      _id_newHashMap as jni$_.JMethodIDPtr,
      i,
    ).object<HashMap<$K?, $V?>?>(
      $HashMap$NullableType$<$K?, $V?>(K.nullableType, V.nullableType),
    );
  }

  static final _id_put = _class.instanceMethodId(
    r'put',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _put =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V put(K object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? put($K? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _put(
      reference.pointer,
      _id_put as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_putAll = _class.instanceMethodId(
    r'putAll',
    r'(Ljava/util/Map;)V',
  );

  static final _putAll =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void putAll(java.util.Map<? extends K, ? extends V> map)`
  void putAll(jni$_.JMap<$K?, $V?>? map) {
    final _$map = map?.reference ?? jni$_.jNullReference;
    _putAll(
      reference.pointer,
      _id_putAll as jni$_.JMethodIDPtr,
      _$map.pointer,
    ).check();
  }

  static final _id_putIfAbsent = _class.instanceMethodId(
    r'putIfAbsent',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _putIfAbsent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V putIfAbsent(K object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? putIfAbsent($K? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _putIfAbsent(
      reference.pointer,
      _id_putIfAbsent as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_remove = _class.instanceMethodId(
    r'remove',
    r'(Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _remove =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V remove(java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? remove(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _remove(
      reference.pointer,
      _id_remove as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_remove$1 = _class.instanceMethodId(
    r'remove',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Z',
  );

  static final _remove$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean remove(java.lang.Object object, java.lang.Object object1)`
  bool remove$1(jni$_.JObject? object, jni$_.JObject? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _remove$1(
      reference.pointer,
      _id_remove$1 as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
    ).boolean;
  }

  static final _id_replace = _class.instanceMethodId(
    r'replace',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;',
  );

  static final _replace =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public V replace(K object, V object1)`
  /// The returned object must be released after use, by calling the [release] method.
  $V? replace($K? object, $V? object1) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _replace(
      reference.pointer,
      _id_replace as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
    ).object<$V?>(V.nullableType);
  }

  static final _id_replace$1 = _class.instanceMethodId(
    r'replace',
    r'(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z',
  );

  static final _replace$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean replace(K object, V object1, V object2)`
  bool replace$1($K? object, $V? object1, $V? object2) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    final _$object2 = object2?.reference ?? jni$_.jNullReference;
    return _replace$1(
      reference.pointer,
      _id_replace$1 as jni$_.JMethodIDPtr,
      _$object.pointer,
      _$object1.pointer,
      _$object2.pointer,
    ).boolean;
  }

  static final _id_replaceAll = _class.instanceMethodId(
    r'replaceAll',
    r'(Ljava/util/function/BiFunction;)V',
  );

  static final _replaceAll =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void replaceAll(java.util.function.BiFunction<? super K, ? super V, ? extends V> biFunction)`
  void replaceAll(jni$_.JObject? biFunction) {
    final _$biFunction = biFunction?.reference ?? jni$_.jNullReference;
    _replaceAll(
      reference.pointer,
      _id_replaceAll as jni$_.JMethodIDPtr,
      _$biFunction.pointer,
    ).check();
  }

  static final _id_size = _class.instanceMethodId(r'size', r'()I');

  static final _size =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int size()`
  int size() {
    return _size(reference.pointer, _id_size as jni$_.JMethodIDPtr).integer;
  }

  static final _id_values = _class.instanceMethodId(
    r'values',
    r'()Ljava/util/Collection;',
  );

  static final _values =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.util.Collection<V> values()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? values() {
    return _values(
      reference.pointer,
      _id_values as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }
}

final class $HashMap$NullableType$<
  $K extends jni$_.JObject?,
  $V extends jni$_.JObject?
>
    extends jni$_.JType<HashMap<$K, $V>?> {
  @jni$_.internal
  final jni$_.JType<$K> K;

  @jni$_.internal
  final jni$_.JType<$V> V;

  @jni$_.internal
  const $HashMap$NullableType$(this.K, this.V);

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/util/HashMap;';

  @jni$_.internal
  @core$_.override
  HashMap<$K, $V>? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : HashMap<$K, $V>.fromReference(K, V, reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<HashMap<$K, $V>?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => Object.hash($HashMap$NullableType$, K, V);

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($HashMap$NullableType$<$K, $V>) &&
        other is $HashMap$NullableType$<$K, $V> &&
        K == other.K &&
        V == other.V;
  }
}

final class $HashMap$Type$<$K extends jni$_.JObject?, $V extends jni$_.JObject?>
    extends jni$_.JType<HashMap<$K, $V>> {
  @jni$_.internal
  final jni$_.JType<$K> K;

  @jni$_.internal
  final jni$_.JType<$V> V;

  @jni$_.internal
  const $HashMap$Type$(this.K, this.V);

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/util/HashMap;';

  @jni$_.internal
  @core$_.override
  HashMap<$K, $V> fromReference(jni$_.JReference reference) =>
      HashMap<$K, $V>.fromReference(K, V, reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<HashMap<$K, $V>?> get nullableType =>
      $HashMap$NullableType$<$K, $V>(K, V);

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => Object.hash($HashMap$Type$, K, V);

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($HashMap$Type$<$K, $V>) &&
        other is $HashMap$Type$<$K, $V> &&
        K == other.K &&
        V == other.V;
  }
}

/// from: `dev.dart.Sample`
class Sample extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<Sample> $type;

  @jni$_.internal
  Sample.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'dev/dart/Sample');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Sample?> nullableType = $Sample$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Sample> type = $Sample$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Sample() {
    return Sample.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_sum = _class.staticMethodId(r'sum', r'(II)I');

  static final _sum =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              int,
            )
          >();

  /// from: `static public int sum(int a, int b)`
  static int sum(int a, int b) {
    return _sum(
      _class.reference.pointer,
      _id_sum as jni$_.JMethodIDPtr,
      a,
      b,
    ).integer;
  }

  static final _id_initTournament = _class.staticMethodId(
    r'initTournament',
    r'(Landroid/app/Activity;Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _initTournament =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public java.lang.String initTournament(android.app.Activity activity, java.lang.String trfFileContent)`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? initTournament(
    jni$_.JObject? activity,
    jni$_.JString? trfFileContent,
  ) {
    final _$activity = activity?.reference ?? jni$_.jNullReference;
    final _$trfFileContent = trfFileContent?.reference ?? jni$_.jNullReference;
    return _initTournament(
      _class.reference.pointer,
      _id_initTournament as jni$_.JMethodIDPtr,
      _$activity.pointer,
      _$trfFileContent.pointer,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $Sample$NullableType$ extends jni$_.JType<Sample?> {
  @jni$_.internal
  const $Sample$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/dart/Sample;';

  @jni$_.internal
  @core$_.override
  Sample? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : Sample.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Sample?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Sample$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Sample$NullableType$) &&
        other is $Sample$NullableType$;
  }
}

final class $Sample$Type$ extends jni$_.JType<Sample> {
  @jni$_.internal
  const $Sample$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/dart/Sample;';

  @jni$_.internal
  @core$_.override
  Sample fromReference(jni$_.JReference reference) =>
      Sample.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<Sample?> get nullableType => const $Sample$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($Sample$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Sample$Type$) && other is $Sample$Type$;
  }
}
